quarkus:

  http:
    port: 8080

  datasource:
    db-kind: postgresql
    username: postgres
    password: password
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres

  flyway:
    migrate-at-start: true
    validate-on-migrate: true