version: '3.1'

services:

  postgres:
    container_name: postgres-quarkus-api
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data